### ISSUE TITLE
README.md needs an update to reflect more recent changes

### ISSUE THREAD

**Issue by Ryan-Millard** [Ryan-Millard/React-Tutorial#3]
Please add descriptions on how users can pull/fork this repository to their local machine as well as explain the purpose of this repository - to serve as a guide for users who have started learning React and foe those who would like to refresh their memory on React's best practices.

I have created a documentation branch. Please folk this repository and submit a pull request to it when ready. Thank you.

**Comment by Shoyebaktar-shirol** [comment]
@Ryan-Millard ,Please assign me this issue and provide some more details to Update your readme.md file .

**Comment by Ryan-Millard** [comment]
Hi. I've assigned this issue to you. Please let me know if you have any further issues. Thank you.

**Comment by Shoyebaktar-shirol** [comment]
@Ryan-Millard  user has to push the changes on main branch or they need to create a new branch.

**Comment by Ryan-Millard** [comment]
> @Ryan-Millard  user has to push the changes on main branch or they need to create a new branch.

The main branch has been modified to have specific rules to ensure that it is protected from all changes from non-admin users. This ensures that accidents can't happen that destroy the code. 

The main branch is the lifeline of the project. Without it, there is no project left. Please fork this repository, make your changes, and then submit a pull request.

**Comment by Shoyebaktar-shirol** [comment]
@Ryan-Millard ,okey

**Comment by Ryan-Millard** [comment]
> @Ryan-Millard , its better to create branch so i make changes.

@Shoyebaktar-shirol, I have done that. Please either use the "documentation" branch or fork this repository, create your own branch, and then submit a pull request.
