### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Ryan-Millard** [Ryan-Millard/React-Tutorial#5]
The source code in the tsx (TypeScript XML) files need to have comments added to them to explain concepts in a clearer manner.

**Comment by Shoyebaktar-shirol** [comment]
@Ryan-Millard hello Assign me this issue i would like to contribute on that .

**Comment by Ryan-Millard** [comment]
> @Ryan-Millard hello Assign me this issue i would like to contribute on that . 

I have assigned you to it. Thank you for your assistance so far in this repo.

**Comment by Shoyebaktar-shirol** [comment]
Hello @Ryan-Millard , Thank you for assigning this issue, as soon as possible I will raise the pull request.
